### ISSUE TITLE
could you please provide the script for data generation?

### ISSUE THREAD

**Issue by liuliu66** [Pearl-UTexas/ScrewNet#1]
Hi, many thanks for this work. And I may want to reproduce the training procedure with my dataset. So could you please provide the data generation script? I have downloaded PartNet-Mobility models and need to render some samples for training. 

BTW, I have another question about the ScrewNet that how it deal with the sample with multiple moving parts? e.g. drawer 3 cols.

Thanks a lot!

**Comment by jainajinkya** [comment]
Hi, as we mentioned in the readme file, you can generate the sample training and test datasets using our fork of SyntheticArticulatedData repo: https://github.com/jainajinkya/SyntheticArticulatedData

ScrewNet estimates the articulation relationship between a pair of rigid objects. In the case of a chest of drawers with 3 drawers, it can iteratively estimate the articulation relationship between each of the drawer and the chest. Note that it will require depth images showing the relative motion between the each of the drawer-chest pair as separate inputs.

**Comment by liuliu66** [comment]
@jainajinkya Hi, thanks for your reply. That helps me a lot. Now, I have another question that is there any visualization script that could transfer the 8-dimensional screw to the actual joint or part 6D pose in camera space? e.g. decomposing 3-dimensional joint axis, 4x4 relative transformation for each moving part...

Thanks!

**Comment by jainajinkya** [comment]
ScrewNet estimates the screw coordinates in an object-centric frame situated at the center of the bounding box of the object. You can transform them into the camera frame either using the available object world pose information in the simulation (available as the object_pose <x,y, z, qw, qx, qy, qz> in the included datasets at dataset_file[<obj_index>]['embedding_and_params'])[-7:]) or for real-world objects, using [ar_tags](http://wiki.ros.org/ar_track_alvar), [Yolo-v4](https://arxiv.org/abs/2004.10934), or [SimTrack](https://github.com/karlpauwels/simtrack). Once you have the screw coordinates in the camera frame, the first three elements correspond to the joint axis orientation $\mathbf{l}$, and the next three elements correspond to the moment vector $\mathbf{m}$ from which the joint axis position can be estimated using the method described in [the reference material](http://web.cs.iastate.edu/~cs577/handouts/plucker-coordinates.pdf). The last two elements correspond to the angular and translational displacements between the two object parts $\theta$ and $d$, respectively. If you wish to estimate the 4X4 transformation matrix between the two object parts, you can construct the corresponding rotation matrix from the angle-axis representation <\mathbf{l}, \theta> and the translation vector $\mathbf{t} = d*\mathbf{l})$, and combine the two together as an affine transform [(More details)](http://web.cs.iastate.edu/~cs577/handouts/dual-quaternion.pdf).
